# Usa la imagen base de Node-RED
FROM nodered/node-red:latest

# Establece el timezone
ENV TZ=America/Santiago

# Instala node-red-dashboard
RUN npm install node-red/node-red-dashboard

# Expone el puerto 1880
EXPOSE 1880
